<?php



$con = mysqli_connect('localhost','root','','barabkund');

$tables = 'CREATE TABLE `1st_year_1st_term_business` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `accounting crtv` int(20) DEFAULT NULL,
    `accounting mcq` int(20) DEFAULT NULL,
    `accounting total` int(20) NOT NULL,
    `accounting total90` int(20) NOT NULL,
    `accounting ct` int(20) DEFAULT NULL,
    `accounting total final` int(20) NOT NULL,
    `accounting lg` varchar(20) NOT NULL,
    `accounting gp` float NOT NULL,
    `business_organization crtv` int(20) DEFAULT NULL,
    `business_organization mcq` int(20) DEFAULT NULL,
    `business_organization total` int(20) NOT NULL,
    `business_organization total90` int(20) NOT NULL,
    `business_organization ct` int(20) DEFAULT NULL,
    `business_organization total final` int(20) NOT NULL,
    `business_organization lg` varchar(20) NOT NULL,
    `business_organization gp` float NOT NULL,
    `production_management crtv` int(20) DEFAULT NULL,
    `production_management mcq` int(20) DEFAULT NULL,
    `production_management total` int(20) NOT NULL,
    `production_management total90` int(20) NOT NULL,
    `production_management ct` int(20) DEFAULT NULL,
    `production_management total final` int(20) NOT NULL,
    `production_management lg` varchar(20) NOT NULL,
    `production_management gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `finance crtv` int(20) DEFAULT NULL,
    `finance mcq` int(20) DEFAULT NULL,
    `finance total` int(20) NOT NULL,
    `finance total90` int(20) NOT NULL,
    `finance ct` int(20) DEFAULT NULL,
    `finance total final` int(20) NOT NULL,
    `finance lg` varchar(20) NOT NULL,
    `finance gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_1st_term_business_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_1st_term_humanities	CREATE TABLE `1st_year_1st_term_humanities` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `civics crtv` int(20) DEFAULT NULL,
    `civics mcq` int(20) DEFAULT NULL,
    `civics total` int(20) NOT NULL,
    `civics total90` int(20) NOT NULL,
    `civics ct` int(20) DEFAULT NULL,
    `civics total final` int(20) NOT NULL,
    `civics lg` varchar(20) NOT NULL,
    `civics gp` float NOT NULL,
    `logic crtv` int(20) DEFAULT NULL,
    `logic mcq` int(20) DEFAULT NULL,
    `logic total` int(20) NOT NULL,
    `logic total90` int(20) NOT NULL,
    `logic ct` int(20) DEFAULT NULL,
    `logic total final` int(20) NOT NULL,
    `logic lg` varchar(20) NOT NULL,
    `logic gp` float NOT NULL,
    `sociology crtv` int(20) DEFAULT NULL,
    `sociology mcq` int(20) DEFAULT NULL,
    `sociology total` int(20) NOT NULL,
    `sociology total90` int(20) NOT NULL,
    `sociology ct` int(20) DEFAULT NULL,
    `sociology total final` int(20) NOT NULL,
    `sociology lg` varchar(20) NOT NULL,
    `sociology gp` float NOT NULL,
    `islamic_history crtv` int(20) DEFAULT NULL,
    `islamic_history mcq` int(20) DEFAULT NULL,
    `islamic_history total` int(20) NOT NULL,
    `islamic_history total90` int(20) NOT NULL,
    `islamic_history ct` int(20) DEFAULT NULL,
    `islamic_history total final` int(20) NOT NULL,
    `islamic_history lg` varchar(20) NOT NULL,
    `islamic_history gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_1st_term_humanities_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_1st_term_science	CREATE TABLE `1st_year_1st_term_science` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `physics crtv` int(11) DEFAULT NULL,
    `physics mcq` int(11) DEFAULT NULL,
    `physics prac` int(11) DEFAULT NULL,
    `physics total` int(11) NOT NULL,
    `physics total90` int(11) NOT NULL,
    `physics ct` int(11) DEFAULT NULL,
    `physics total final` int(11) NOT NULL,
    `physics lg` varchar(11) NOT NULL,
    `physics gp` float NOT NULL,
    `chemistry crtv` int(11) DEFAULT NULL,
    `chemistry mcq` int(11) DEFAULT NULL,
    `chemistry prac` int(11) DEFAULT NULL,
    `chemistry total` int(11) NOT NULL,
    `chemistry total90` int(11) NOT NULL,
    `chemistry ct` int(11) DEFAULT NULL,
    `chemistry total final` int(11) NOT NULL,
    `chemistry lg` varchar(11) NOT NULL,
    `chemistry gp` float NOT NULL,
    `biology crtv` int(11) DEFAULT NULL,
    `biology mcq` int(11) DEFAULT NULL,
    `biology prac` int(11) DEFAULT NULL,
    `biology total` int(11) NOT NULL,
    `biology total90` int(11) NOT NULL,
    `biology ct` int(11) DEFAULT NULL,
    `biology total final` int(11) NOT NULL,
    `biology lg` varchar(11) NOT NULL,
    `biology gp` float NOT NULL,
    `math crtv` int(11) DEFAULT NULL,
    `math mcq` int(11) DEFAULT NULL,
    `math prac` int(11) DEFAULT NULL,
    `math total` int(11) NOT NULL,
    `math total90` int(11) NOT NULL,
    `math ct` int(11) DEFAULT NULL,
    `math total final` int(11) NOT NULL,
    `math lg` varchar(11) NOT NULL,
    `math gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_1st_term_science_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_2nd_term_business	CREATE TABLE `1st_year_2nd_term_business` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `accounting crtv` int(20) DEFAULT NULL,
    `accounting mcq` int(20) DEFAULT NULL,
    `accounting total` int(20) NOT NULL,
    `accounting total90` int(20) NOT NULL,
    `accounting ct` int(20) DEFAULT NULL,
    `accounting total final` int(20) NOT NULL,
    `accounting lg` varchar(20) NOT NULL,
    `accounting gp` float NOT NULL,
    `business_organization crtv` int(20) DEFAULT NULL,
    `business_organization mcq` int(20) DEFAULT NULL,
    `business_organization total` int(20) NOT NULL,
    `business_organization total90` int(20) NOT NULL,
    `business_organization ct` int(20) DEFAULT NULL,
    `business_organization total final` int(20) NOT NULL,
    `business_organization lg` varchar(20) NOT NULL,
    `business_organization gp` float NOT NULL,
    `production_management crtv` int(20) DEFAULT NULL,
    `production_management mcq` int(20) DEFAULT NULL,
    `production_management total` int(20) NOT NULL,
    `production_management total90` int(20) NOT NULL,
    `production_management ct` int(20) DEFAULT NULL,
    `production_management total final` int(20) NOT NULL,
    `production_management lg` varchar(20) NOT NULL,
    `production_management gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `finance crtv` int(20) DEFAULT NULL,
    `finance mcq` int(20) DEFAULT NULL,
    `finance total` int(20) NOT NULL,
    `finance total90` int(20) NOT NULL,
    `finance ct` int(20) DEFAULT NULL,
    `finance total final` int(20) NOT NULL,
    `finance lg` varchar(20) NOT NULL,
    `finance gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_2nd_term_business_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_2nd_term_humanities	CREATE TABLE `1st_year_2nd_term_humanities` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `civics crtv` int(20) DEFAULT NULL,
    `civics mcq` int(20) DEFAULT NULL,
    `civics total` int(20) NOT NULL,
    `civics total90` int(20) NOT NULL,
    `civics ct` int(20) DEFAULT NULL,
    `civics total final` int(20) NOT NULL,
    `civics lg` varchar(20) NOT NULL,
    `civics gp` float NOT NULL,
    `logic crtv` int(20) DEFAULT NULL,
    `logic mcq` int(20) DEFAULT NULL,
    `logic total` int(20) NOT NULL,
    `logic total90` int(20) NOT NULL,
    `logic ct` int(20) DEFAULT NULL,
    `logic total final` int(20) NOT NULL,
    `logic lg` varchar(20) NOT NULL,
    `logic gp` float NOT NULL,
    `sociology crtv` int(20) DEFAULT NULL,
    `sociology mcq` int(20) DEFAULT NULL,
    `sociology total` int(20) NOT NULL,
    `sociology total90` int(20) NOT NULL,
    `sociology ct` int(20) DEFAULT NULL,
    `sociology total final` int(20) NOT NULL,
    `sociology lg` varchar(20) NOT NULL,
    `sociology gp` float NOT NULL,
    `islamic_history crtv` int(20) DEFAULT NULL,
    `islamic_history mcq` int(20) DEFAULT NULL,
    `islamic_history total` int(20) NOT NULL,
    `islamic_history total90` int(20) NOT NULL,
    `islamic_history ct` int(20) DEFAULT NULL,
    `islamic_history total final` int(20) NOT NULL,
    `islamic_history lg` varchar(20) NOT NULL,
    `islamic_history gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_2nd_term_humanities_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_2nd_term_science	CREATE TABLE `1st_year_2nd_term_science` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `physics crtv` int(11) DEFAULT NULL,
    `physics mcq` int(11) DEFAULT NULL,
    `physics prac` int(11) DEFAULT NULL,
    `physics total` int(11) NOT NULL,
    `physics total90` int(11) NOT NULL,
    `physics ct` int(11) DEFAULT NULL,
    `physics total final` int(11) NOT NULL,
    `physics lg` varchar(11) NOT NULL,
    `physics gp` float NOT NULL,
    `chemistry crtv` int(11) DEFAULT NULL,
    `chemistry mcq` int(11) DEFAULT NULL,
    `chemistry prac` int(11) DEFAULT NULL,
    `chemistry total` int(11) NOT NULL,
    `chemistry total90` int(11) NOT NULL,
    `chemistry ct` int(11) DEFAULT NULL,
    `chemistry total final` int(11) NOT NULL,
    `chemistry lg` varchar(11) NOT NULL,
    `chemistry gp` float NOT NULL,
    `biology crtv` int(11) DEFAULT NULL,
    `biology mcq` int(11) DEFAULT NULL,
    `biology prac` int(11) DEFAULT NULL,
    `biology total` int(11) NOT NULL,
    `biology total90` int(11) NOT NULL,
    `biology ct` int(11) DEFAULT NULL,
    `biology total final` int(11) NOT NULL,
    `biology lg` varchar(11) NOT NULL,
    `biology gp` float NOT NULL,
    `math crtv` int(11) DEFAULT NULL,
    `math mcq` int(11) DEFAULT NULL,
    `math prac` int(11) DEFAULT NULL,
    `math total` int(11) NOT NULL,
    `math total90` int(11) NOT NULL,
    `math ct` int(11) DEFAULT NULL,
    `math total final` int(11) NOT NULL,
    `math lg` varchar(11) NOT NULL,
    `math gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_2nd_term_science_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_final_business	CREATE TABLE `1st_year_final_business` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `accounting crtv` int(20) DEFAULT NULL,
    `accounting mcq` int(20) DEFAULT NULL,
    `accounting total` int(20) NOT NULL,
    `accounting total90` int(20) NOT NULL,
    `accounting ct` int(20) DEFAULT NULL,
    `accounting total final` int(20) NOT NULL,
    `accounting lg` varchar(20) NOT NULL,
    `accounting gp` float NOT NULL,
    `business_organization crtv` int(20) DEFAULT NULL,
    `business_organization mcq` int(20) DEFAULT NULL,
    `business_organization total` int(20) NOT NULL,
    `business_organization total90` int(20) NOT NULL,
    `business_organization ct` int(20) DEFAULT NULL,
    `business_organization total final` int(20) NOT NULL,
    `business_organization lg` varchar(20) NOT NULL,
    `business_organization gp` float NOT NULL,
    `production_management crtv` int(20) DEFAULT NULL,
    `production_management mcq` int(20) DEFAULT NULL,
    `production_management total` int(20) NOT NULL,
    `production_management total90` int(20) NOT NULL,
    `production_management ct` int(20) DEFAULT NULL,
    `production_management total final` int(20) NOT NULL,
    `production_management lg` varchar(20) NOT NULL,
    `production_management gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `finance crtv` int(20) DEFAULT NULL,
    `finance mcq` int(20) DEFAULT NULL,
    `finance total` int(20) NOT NULL,
    `finance total90` int(20) NOT NULL,
    `finance ct` int(20) DEFAULT NULL,
    `finance total final` int(20) NOT NULL,
    `finance lg` varchar(20) NOT NULL,
    `finance gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_final_business_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_final_humanities	CREATE TABLE `1st_year_final_humanities` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `civics crtv` int(20) DEFAULT NULL,
    `civics mcq` int(20) DEFAULT NULL,
    `civics total` int(20) NOT NULL,
    `civics total90` int(20) NOT NULL,
    `civics ct` int(20) DEFAULT NULL,
    `civics total final` int(20) NOT NULL,
    `civics lg` varchar(20) NOT NULL,
    `civics gp` float NOT NULL,
    `logic crtv` int(20) DEFAULT NULL,
    `logic mcq` int(20) DEFAULT NULL,
    `logic total` int(20) NOT NULL,
    `logic total90` int(20) NOT NULL,
    `logic ct` int(20) DEFAULT NULL,
    `logic total final` int(20) NOT NULL,
    `logic lg` varchar(20) NOT NULL,
    `logic gp` float NOT NULL,
    `sociology crtv` int(20) DEFAULT NULL,
    `sociology mcq` int(20) DEFAULT NULL,
    `sociology total` int(20) NOT NULL,
    `sociology total90` int(20) NOT NULL,
    `sociology ct` int(20) DEFAULT NULL,
    `sociology total final` int(20) NOT NULL,
    `sociology lg` varchar(20) NOT NULL,
    `sociology gp` float NOT NULL,
    `islamic_history crtv` int(20) DEFAULT NULL,
    `islamic_history mcq` int(20) DEFAULT NULL,
    `islamic_history total` int(20) NOT NULL,
    `islamic_history total90` int(20) NOT NULL,
    `islamic_history ct` int(20) DEFAULT NULL,
    `islamic_history total final` int(20) NOT NULL,
    `islamic_history lg` varchar(20) NOT NULL,
    `islamic_history gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_final_humanities_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   1st_year_final_science	CREATE TABLE `1st_year_final_science` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `physics crtv` int(11) DEFAULT NULL,
    `physics mcq` int(11) DEFAULT NULL,
    `physics prac` int(11) DEFAULT NULL,
    `physics total` int(11) NOT NULL,
    `physics total90` int(11) NOT NULL,
    `physics ct` int(11) DEFAULT NULL,
    `physics total final` int(11) NOT NULL,
    `physics lg` varchar(11) NOT NULL,
    `physics gp` float NOT NULL,
    `chemistry crtv` int(11) DEFAULT NULL,
    `chemistry mcq` int(11) DEFAULT NULL,
    `chemistry prac` int(11) DEFAULT NULL,
    `chemistry total` int(11) NOT NULL,
    `chemistry total90` int(11) NOT NULL,
    `chemistry ct` int(11) DEFAULT NULL,
    `chemistry total final` int(11) NOT NULL,
    `chemistry lg` varchar(11) NOT NULL,
    `chemistry gp` float NOT NULL,
    `biology crtv` int(11) DEFAULT NULL,
    `biology mcq` int(11) DEFAULT NULL,
    `biology prac` int(11) DEFAULT NULL,
    `biology total` int(11) NOT NULL,
    `biology total90` int(11) NOT NULL,
    `biology ct` int(11) DEFAULT NULL,
    `biology total final` int(11) NOT NULL,
    `biology lg` varchar(11) NOT NULL,
    `biology gp` float NOT NULL,
    `math crtv` int(11) DEFAULT NULL,
    `math mcq` int(11) DEFAULT NULL,
    `math prac` int(11) DEFAULT NULL,
    `math total` int(11) NOT NULL,
    `math total90` int(11) NOT NULL,
    `math ct` int(11) DEFAULT NULL,
    `math total final` int(11) NOT NULL,
    `math lg` varchar(11) NOT NULL,
    `math gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `1st_year_final_science_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_accounting_business	CREATE TABLE `ct_mark_accounting_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_accounting_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_bangla_business	CREATE TABLE `ct_mark_bangla_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `Email` varchar(255) DEFAULT NULL,
    `ct2` varchar(255) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    KEY `Student_ID` (`Student_ID`),
    CONSTRAINT `ct_mark_bangla_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_bangla_humanities	CREATE TABLE `ct_mark_bangla_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_bangla_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_bangla_science	CREATE TABLE `ct_mark_bangla_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_bangla_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_biology_science	CREATE TABLE `ct_mark_biology_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_biology_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_business_organization_business	CREATE TABLE `ct_mark_business_organization_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_business_organization_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_chemistry_science	CREATE TABLE `ct_mark_chemistry_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    `ct_6` int(20) DEFAULT NULL,
    `ct_7` int(20) DEFAULT NULL,
    `ct_8` int(20) DEFAULT NULL,
    `ct_9` int(20) DEFAULT NULL,
    `ct_10` int(20) DEFAULT NULL,
    `ct_11` int(20) DEFAULT NULL,
    `ct_12` int(20) DEFAULT NULL,
    `ct_13` int(20) DEFAULT NULL,
    `ct_14` int(20) DEFAULT NULL,
    `ct_15` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_chemistry_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_civics_humanities	CREATE TABLE `ct_mark_civics_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    `ct_6` int(20) DEFAULT NULL,
    `ct_7` int(20) DEFAULT NULL,
    `ct_8` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_civics_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_economics_business	CREATE TABLE `ct_mark_economics_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_economics_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_economics_humanities	CREATE TABLE `ct_mark_economics_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_economics_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_english_business	CREATE TABLE `ct_mark_english_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_english_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_english_humanities	CREATE TABLE `ct_mark_english_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_english_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_english_science	CREATE TABLE `ct_mark_english_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_english_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_finance_business	CREATE TABLE `ct_mark_finance_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_finance_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_ict_business	CREATE TABLE `ct_mark_ict_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_ict_humanities	CREATE TABLE `ct_mark_ict_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_ict_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_ict_science	CREATE TABLE `ct_mark_ict_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_ict_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_islamic_history_humanities	CREATE TABLE `ct_mark_islamic_history_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_islamic_history_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_logic_humanities	CREATE TABLE `ct_mark_logic_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_logic_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_math_science	CREATE TABLE `ct_mark_math_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_math_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_physics_science	CREATE TABLE `ct_mark_physics_science` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    `ct_6` int(20) DEFAULT NULL,
    `ct_7` int(20) DEFAULT NULL,
    `ct_8` int(20) DEFAULT NULL,
    `ct_9` int(20) DEFAULT NULL,
    `ct_10` int(20) DEFAULT NULL,
    `ct_11` int(20) DEFAULT NULL,
    `ct_12` int(20) DEFAULT NULL,
    `ct_13` int(20) DEFAULT NULL,
    `ct_14` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_physics_science_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_production_management_business	CREATE TABLE `ct_mark_production_management_business` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_production_management_business_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   ct_mark_sociology_humanities	CREATE TABLE `ct_mark_sociology_humanities` (
    `Student_ID` varchar(200) NOT NULL,
    `ct1` int(11) NOT NULL,
    `ct_2` int(20) DEFAULT NULL,
    `ct_3` int(20) DEFAULT NULL,
    `ct_4` int(20) DEFAULT NULL,
    `ct_5` int(20) DEFAULT NULL,
    PRIMARY KEY (`Student_ID`),
    CONSTRAINT `ct_mark_sociology_humanities_ibfk_1` FOREIGN KEY (`Student_ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   pre_test_business	CREATE TABLE `pre_test_business` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `accounting crtv` int(20) DEFAULT NULL,
    `accounting mcq` int(20) DEFAULT NULL,
    `accounting total` int(20) NOT NULL,
    `accounting total90` int(20) NOT NULL,
    `accounting ct` int(20) DEFAULT NULL,
    `accounting total final` int(20) NOT NULL,
    `accounting lg` varchar(20) NOT NULL,
    `accounting gp` float NOT NULL,
    `business_organization crtv` int(20) DEFAULT NULL,
    `business_organization mcq` int(20) DEFAULT NULL,
    `business_organization total` int(20) NOT NULL,
    `business_organization total90` int(20) NOT NULL,
    `business_organization ct` int(20) DEFAULT NULL,
    `business_organization total final` int(20) NOT NULL,
    `business_organization lg` varchar(20) NOT NULL,
    `business_organization gp` float NOT NULL,
    `production_management crtv` int(20) DEFAULT NULL,
    `production_management mcq` int(20) DEFAULT NULL,
    `production_management total` int(20) NOT NULL,
    `production_management total90` int(20) NOT NULL,
    `production_management ct` int(20) DEFAULT NULL,
    `production_management total final` int(20) NOT NULL,
    `production_management lg` varchar(20) NOT NULL,
    `production_management gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `finance crtv` int(20) DEFAULT NULL,
    `finance mcq` int(20) DEFAULT NULL,
    `finance total` int(20) NOT NULL,
    `finance total90` int(20) NOT NULL,
    `finance ct` int(20) DEFAULT NULL,
    `finance total final` int(20) NOT NULL,
    `finance lg` varchar(20) NOT NULL,
    `finance gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `pre_test_business_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_business` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   pre_test_humanities	CREATE TABLE `pre_test_humanities` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `civics crtv` int(20) DEFAULT NULL,
    `civics mcq` int(20) DEFAULT NULL,
    `civics total` int(20) NOT NULL,
    `civics total90` int(20) NOT NULL,
    `civics ct` int(20) DEFAULT NULL,
    `civics total final` int(20) NOT NULL,
    `civics lg` varchar(20) NOT NULL,
    `civics gp` float NOT NULL,
    `logic crtv` int(20) DEFAULT NULL,
    `logic mcq` int(20) DEFAULT NULL,
    `logic total` int(20) NOT NULL,
    `logic total90` int(20) NOT NULL,
    `logic ct` int(20) DEFAULT NULL,
    `logic total final` int(20) NOT NULL,
    `logic lg` varchar(20) NOT NULL,
    `logic gp` float NOT NULL,
    `sociology crtv` int(20) DEFAULT NULL,
    `sociology mcq` int(20) DEFAULT NULL,
    `sociology total` int(20) NOT NULL,
    `sociology total90` int(20) NOT NULL,
    `sociology ct` int(20) DEFAULT NULL,
    `sociology total final` int(20) NOT NULL,
    `sociology lg` varchar(20) NOT NULL,
    `sociology gp` float NOT NULL,
    `islamic_history crtv` int(20) DEFAULT NULL,
    `islamic_history mcq` int(20) DEFAULT NULL,
    `islamic_history total` int(20) NOT NULL,
    `islamic_history total90` int(20) NOT NULL,
    `islamic_history ct` int(20) DEFAULT NULL,
    `islamic_history total final` int(20) NOT NULL,
    `islamic_history lg` varchar(20) NOT NULL,
    `islamic_history gp` float NOT NULL,
    `economics crtv` int(20) DEFAULT NULL,
    `economics mcq` int(20) DEFAULT NULL,
    `economics total` int(20) NOT NULL,
    `economics total90` int(20) NOT NULL,
    `economics ct` int(20) DEFAULT NULL,
    `economics total final` int(20) NOT NULL,
    `economics lg` varchar(20) NOT NULL,
    `economics gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `pre_test_humanities_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   pre_test_science	CREATE TABLE `pre_test_science` (
    `Student ID` varchar(20) NOT NULL,
    `bangla crtv` int(11) DEFAULT NULL,
    `bangla mcq` int(11) DEFAULT NULL,
    `bangla total` int(11) NOT NULL,
    `bangla total90` int(11) NOT NULL,
    `bangla ct` int(11) DEFAULT NULL,
    `bangla total final` int(11) NOT NULL,
    `bangla lg` varchar(11) NOT NULL,
    `bangla gp` float NOT NULL,
    `english` int(11) DEFAULT NULL,
    `english90` int(11) NOT NULL,
    `english ct` int(11) DEFAULT NULL,
    `english total final` int(11) NOT NULL,
    `english lg` varchar(11) NOT NULL,
    `english gp` float NOT NULL,
    `ict crtv` int(11) DEFAULT NULL,
    `ict mcq` int(11) DEFAULT NULL,
    `ict prac` int(11) DEFAULT NULL,
    `ict total` int(11) NOT NULL,
    `ict total90` int(11) NOT NULL,
    `ict ct` int(11) DEFAULT NULL,
    `ict total final` int(11) NOT NULL,
    `ict lg` varchar(11) NOT NULL,
    `ict gp` float NOT NULL,
    `physics crtv` int(11) DEFAULT NULL,
    `physics mcq` int(11) DEFAULT NULL,
    `physics prac` int(11) DEFAULT NULL,
    `physics total` int(11) NOT NULL,
    `physics total90` int(11) NOT NULL,
    `physics ct` int(11) DEFAULT NULL,
    `physics total final` int(11) NOT NULL,
    `physics lg` varchar(11) NOT NULL,
    `physics gp` float NOT NULL,
    `chemistry crtv` int(11) DEFAULT NULL,
    `chemistry mcq` int(11) DEFAULT NULL,
    `chemistry prac` int(11) DEFAULT NULL,
    `chemistry total` int(11) NOT NULL,
    `chemistry total90` int(11) NOT NULL,
    `chemistry ct` int(11) DEFAULT NULL,
    `chemistry total final` int(11) NOT NULL,
    `chemistry lg` varchar(11) NOT NULL,
    `chemistry gp` float NOT NULL,
    `biology crtv` int(11) DEFAULT NULL,
    `biology mcq` int(11) DEFAULT NULL,
    `biology prac` int(11) DEFAULT NULL,
    `biology total` int(11) NOT NULL,
    `biology total90` int(11) NOT NULL,
    `biology ct` int(11) DEFAULT NULL,
    `biology total final` int(11) NOT NULL,
    `biology lg` varchar(11) NOT NULL,
    `biology gp` float NOT NULL,
    `math crtv` int(11) DEFAULT NULL,
    `math mcq` int(11) DEFAULT NULL,
    `math prac` int(11) DEFAULT NULL,
    `math total` int(11) NOT NULL,
    `math total90` int(11) NOT NULL,
    `math ct` int(11) DEFAULT NULL,
    `math total final` int(11) NOT NULL,
    `math lg` varchar(11) NOT NULL,
    `math gp` float NOT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `pre_test_science_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   student_info_business	CREATE TABLE `student_info_business` (
    `student_id` varchar(20) NOT NULL,
    `student_name` varchar(100) NOT NULL,
    `year` varchar(20) NOT NULL,
    `student_group` varchar(20) NOT NULL,
    `fathers_name` varchar(100) NOT NULL,
    `mothers_name` varchar(100) NOT NULL,
    `date_of_birth` date NOT NULL,
    `present_address` varchar(500) NOT NULL,
    `permanent_address` varchar(500) NOT NULL,
    `phone_no` varchar(20) NOT NULL,
    `gaurdian_phone_no` varchar(20) NOT NULL,
    `blood_group` varchar(10) NOT NULL,
    `image` blob NOT NULL,
    `subject1` varchar(50) NOT NULL,
    `subject2` varchar(50) NOT NULL,
    `subject3` varchar(50) NOT NULL,
    `fourth_sub` varchar(50) NOT NULL,
    PRIMARY KEY (`student_id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   student_info_humanities	CREATE TABLE `student_info_humanities` (
    `student_id` varchar(20) NOT NULL,
    `student_name` varchar(100) NOT NULL,
    `year` varchar(20) NOT NULL,
    `student_group` varchar(20) NOT NULL,
    `fathers_name` varchar(100) NOT NULL,
    `mothers_name` varchar(100) NOT NULL,
    `date_of_birth` date NOT NULL,
    `present_address` varchar(500) NOT NULL,
    `permanent_address` varchar(500) NOT NULL,
    `phone_no` varchar(20) NOT NULL,
    `gaurdian_phone_no` varchar(20) NOT NULL,
    `blood_group` varchar(10) NOT NULL,
    `image` blob NOT NULL,
    `subject1` varchar(50) NOT NULL,
    `subject2` varchar(50) NOT NULL,
    `subject3` varchar(50) NOT NULL,
    `fourth_sub` varchar(20) NOT NULL,
    PRIMARY KEY (`student_id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   student_info_science	CREATE TABLE `student_info_science` (
    `student_id` varchar(20) NOT NULL,
    `student_name` varchar(100) NOT NULL,
    `year` varchar(20) NOT NULL,
    `student_group` varchar(20) NOT NULL,
    `fathers_name` varchar(100) NOT NULL,
    `mothers_name` varchar(100) NOT NULL,
    `date_of_birth` date NOT NULL,
    `present_address` varchar(500) NOT NULL,
    `permanent_address` varchar(500) NOT NULL,
    `phone_no` varchar(20) NOT NULL,
    `gaurdian_phone_no` varchar(20) NOT NULL,
    `blood_group` varchar(10) NOT NULL,
    `image` blob NOT NULL,
    `subject1` varchar(50) NOT NULL,
    `subject2` varchar(50) NOT NULL,
    `subject3` varchar(50) NOT NULL,
    `fourth_sub` varchar(20) NOT NULL,
    PRIMARY KEY (`student_id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   test_business	CREATE TABLE `test_business` (
    `Student ID` varchar(20) NOT NULL,
    `bangla1 crtv` int(11) DEFAULT NULL,
    `bangla1 mcq` int(11) DEFAULT NULL,
    `bangla1 total` int(11) DEFAULT NULL,
    `bangla2 crtv` int(20) DEFAULT NULL,
    `bangla2 mcq` int(20) DEFAULT NULL,
    `bangla2 total` int(20) DEFAULT NULL,
    `bangla avg` float DEFAULT NULL,
    `bangla lg` varchar(11) DEFAULT NULL,
    `bangla gp` float DEFAULT NULL,
    `english1` int(20) DEFAULT NULL,
    `english2` int(20) DEFAULT NULL,
    `english avg` int(20) DEFAULT NULL,
    `english lg` varchar(20) DEFAULT NULL,
    `english gp` float DEFAULT NULL,
    `ict crtv` int(20) DEFAULT NULL,
    `ict mcq` int(20) DEFAULT NULL,
    `ict prac` int(20) DEFAULT NULL,
    `ict total` int(20) DEFAULT NULL,
    `ict lg` varchar(20) DEFAULT NULL,
    `ict gp` float DEFAULT NULL,
    `physics1 crtv` int(20) DEFAULT NULL,
    `physics1 mcq` int(20) DEFAULT NULL,
    `physics1 prac` int(20) DEFAULT NULL,
    `physics1 total` int(20) DEFAULT NULL,
    `physics2 crtv` int(20) DEFAULT NULL,
    `physics2 mcq` int(20) DEFAULT NULL,
    `physics2 prac` int(20) DEFAULT NULL,
    `physics2 total` int(20) DEFAULT NULL,
    `physics avg` int(20) DEFAULT NULL,
    `physics lg` varchar(10) DEFAULT NULL,
    `physics gp` float DEFAULT NULL,
    `chemistry1 crtv` int(20) DEFAULT NULL,
    `chemistry1 mcq` int(20) DEFAULT NULL,
    `chemistry1 prac` int(20) DEFAULT NULL,
    `chemistry1 total` int(20) DEFAULT NULL,
    `chemistry2 crtv` int(20) DEFAULT NULL,
    `chemistry2 mcq` int(20) DEFAULT NULL,
    `chemistry2 prac` int(20) DEFAULT NULL,
    `chemistry2 total` int(20) DEFAULT NULL,
    `chemistry avg` int(20) DEFAULT NULL,
    `chemistry lg` varchar(20) DEFAULT NULL,
    `chemistry gp` float DEFAULT NULL,
    `biology1 crtv` int(20) DEFAULT NULL,
    `biology1 mcq` int(20) DEFAULT NULL,
    `biology1 prac` int(20) DEFAULT NULL,
    `biology1 total` int(20) DEFAULT NULL,
    `biology2 crtv` int(20) DEFAULT NULL,
    `biology2 mcq` int(20) DEFAULT NULL,
    `biology2 prac` int(20) DEFAULT NULL,
    `biology2 total` int(20) DEFAULT NULL,
    `biology avg` int(20) DEFAULT NULL,
    `biology lg` varchar(20) DEFAULT NULL,
    `biology gp` float DEFAULT NULL,
    `math1 crtv` int(20) DEFAULT NULL,
    `math1 mcq` int(20) DEFAULT NULL,
    `math1 prac` int(20) DEFAULT NULL,
    `math1 total` int(20) DEFAULT NULL,
    `math2 crtv` int(20) DEFAULT NULL,
    `math2 mcq` int(20) DEFAULT NULL,
    `math2 prac` int(20) DEFAULT NULL,
    `math2 total` int(20) DEFAULT NULL,
    `math avg` int(20) DEFAULT NULL,
    `math lg` varchar(20) DEFAULT NULL,
    `math gp` float DEFAULT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `test_business_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   test_humanities	CREATE TABLE `test_humanities` (
    `Student ID` varchar(20) NOT NULL,
    `bangla1 crtv` int(11) DEFAULT NULL,
    `bangla1 mcq` int(11) DEFAULT NULL,
    `bangla1 total` int(11) DEFAULT NULL,
    `bangla2 crtv` int(20) DEFAULT NULL,
    `bangla2 mcq` int(20) DEFAULT NULL,
    `bangla2 total` int(20) DEFAULT NULL,
    `bangla avg` float DEFAULT NULL,
    `bangla lg` varchar(11) DEFAULT NULL,
    `bangla gp` float DEFAULT NULL,
    `english1` int(20) DEFAULT NULL,
    `english2` int(20) DEFAULT NULL,
    `english avg` int(20) DEFAULT NULL,
    `english lg` varchar(20) DEFAULT NULL,
    `english gp` float DEFAULT NULL,
    `ict crtv` int(20) DEFAULT NULL,
    `ict mcq` int(20) DEFAULT NULL,
    `ict prac` int(20) DEFAULT NULL,
    `ict total` int(20) DEFAULT NULL,
    `ict lg` varchar(20) DEFAULT NULL,
    `ict gp` float DEFAULT NULL,
    `physics1 crtv` int(20) DEFAULT NULL,
    `physics1 mcq` int(20) DEFAULT NULL,
    `physics1 prac` int(20) DEFAULT NULL,
    `physics1 total` int(20) DEFAULT NULL,
    `physics2 crtv` int(20) DEFAULT NULL,
    `physics2 mcq` int(20) DEFAULT NULL,
    `physics2 prac` int(20) DEFAULT NULL,
    `physics2 total` int(20) DEFAULT NULL,
    `physics avg` int(20) DEFAULT NULL,
    `physics lg` varchar(10) DEFAULT NULL,
    `physics gp` float DEFAULT NULL,
    `chemistry1 crtv` int(20) DEFAULT NULL,
    `chemistry1 mcq` int(20) DEFAULT NULL,
    `chemistry1 prac` int(20) DEFAULT NULL,
    `chemistry1 total` int(20) DEFAULT NULL,
    `chemistry2 crtv` int(20) DEFAULT NULL,
    `chemistry2 mcq` int(20) DEFAULT NULL,
    `chemistry2 prac` int(20) DEFAULT NULL,
    `chemistry2 total` int(20) DEFAULT NULL,
    `chemistry avg` int(20) DEFAULT NULL,
    `chemistry lg` varchar(20) DEFAULT NULL,
    `chemistry gp` float DEFAULT NULL,
    `biology1 crtv` int(20) DEFAULT NULL,
    `biology1 mcq` int(20) DEFAULT NULL,
    `biology1 prac` int(20) DEFAULT NULL,
    `biology1 total` int(20) DEFAULT NULL,
    `biology2 crtv` int(20) DEFAULT NULL,
    `biology2 mcq` int(20) DEFAULT NULL,
    `biology2 prac` int(20) DEFAULT NULL,
    `biology2 total` int(20) DEFAULT NULL,
    `biology avg` int(20) DEFAULT NULL,
    `biology lg` varchar(20) DEFAULT NULL,
    `biology gp` float DEFAULT NULL,
    `math1 crtv` int(20) DEFAULT NULL,
    `math1 mcq` int(20) DEFAULT NULL,
    `math1 prac` int(20) DEFAULT NULL,
    `math1 total` int(20) DEFAULT NULL,
    `math2 crtv` int(20) DEFAULT NULL,
    `math2 mcq` int(20) DEFAULT NULL,
    `math2 prac` int(20) DEFAULT NULL,
    `math2 total` int(20) DEFAULT NULL,
    `math avg` int(20) DEFAULT NULL,
    `math lg` varchar(20) DEFAULT NULL,
    `math gp` float DEFAULT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `test_humanities_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_humanities` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   test_science	CREATE TABLE `test_science` (
    `Student ID` varchar(20) NOT NULL,
    `bangla1 crtv` int(11) DEFAULT NULL,
    `bangla1 mcq` int(11) DEFAULT NULL,
    `bangla1 total` int(11) DEFAULT NULL,
    `bangla2 crtv` int(20) DEFAULT NULL,
    `bangla2 mcq` int(20) DEFAULT NULL,
    `bangla2 total` int(20) DEFAULT NULL,
    `bangla avg` float DEFAULT NULL,
    `bangla lg` varchar(11) DEFAULT NULL,
    `bangla gp` float DEFAULT NULL,
    `english1` int(20) DEFAULT NULL,
    `english2` int(20) DEFAULT NULL,
    `english avg` int(20) DEFAULT NULL,
    `english lg` varchar(20) DEFAULT NULL,
    `english gp` float DEFAULT NULL,
    `ict crtv` int(20) DEFAULT NULL,
    `ict mcq` int(20) DEFAULT NULL,
    `ict prac` int(20) DEFAULT NULL,
    `ict total` int(20) DEFAULT NULL,
    `ict lg` varchar(20) DEFAULT NULL,
    `ict gp` float DEFAULT NULL,
    `physics1 crtv` int(20) DEFAULT NULL,
    `physics1 mcq` int(20) DEFAULT NULL,
    `physics1 prac` int(20) DEFAULT NULL,
    `physics1 total` int(20) DEFAULT NULL,
    `physics2 crtv` int(20) DEFAULT NULL,
    `physics2 mcq` int(20) DEFAULT NULL,
    `physics2 prac` int(20) DEFAULT NULL,
    `physics2 total` int(20) DEFAULT NULL,
    `physics avg` int(20) DEFAULT NULL,
    `physics lg` varchar(10) DEFAULT NULL,
    `physics gp` float DEFAULT NULL,
    `chemistry1 crtv` int(20) DEFAULT NULL,
    `chemistry1 mcq` int(20) DEFAULT NULL,
    `chemistry1 prac` int(20) DEFAULT NULL,
    `chemistry1 total` int(20) DEFAULT NULL,
    `chemistry2 crtv` int(20) DEFAULT NULL,
    `chemistry2 mcq` int(20) DEFAULT NULL,
    `chemistry2 prac` int(20) DEFAULT NULL,
    `chemistry2 total` int(20) DEFAULT NULL,
    `chemistry avg` int(20) DEFAULT NULL,
    `chemistry lg` varchar(20) DEFAULT NULL,
    `chemistry gp` float DEFAULT NULL,
    `biology1 crtv` int(20) DEFAULT NULL,
    `biology1 mcq` int(20) DEFAULT NULL,
    `biology1 prac` int(20) DEFAULT NULL,
    `biology1 total` int(20) DEFAULT NULL,
    `biology2 crtv` int(20) DEFAULT NULL,
    `biology2 mcq` int(20) DEFAULT NULL,
    `biology2 prac` int(20) DEFAULT NULL,
    `biology2 total` int(20) DEFAULT NULL,
    `biology avg` int(20) DEFAULT NULL,
    `biology lg` varchar(20) DEFAULT NULL,
    `biology gp` float DEFAULT NULL,
    `math1 crtv` int(20) DEFAULT NULL,
    `math1 mcq` int(20) DEFAULT NULL,
    `math1 prac` int(20) DEFAULT NULL,
    `math1 total` int(20) DEFAULT NULL,
    `math2 crtv` int(20) DEFAULT NULL,
    `math2 mcq` int(20) DEFAULT NULL,
    `math2 prac` int(20) DEFAULT NULL,
    `math2 total` int(20) DEFAULT NULL,
    `math avg` int(20) DEFAULT NULL,
    `math lg` varchar(20) DEFAULT NULL,
    `math gp` float DEFAULT NULL,
    `fourth_sub` varchar(30) NOT NULL,
    `total gp` float NOT NULL,
    `point_from_4th` float NOT NULL,
    `gpa without 4th` float NOT NULL,
    `gpa` float NOT NULL,
    `grade` varchar(20) NOT NULL,
    PRIMARY KEY (`Student ID`),
    CONSTRAINT `test_science_ibfk_1` FOREIGN KEY (`Student ID`) REFERENCES `student_info_science` (`student_id`) ON DELETE CASCADE ON UPDATE CASCADE
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   user_subject	CREATE TABLE `user_subject` (
    `Subject_ID` varchar(200) NOT NULL,
    `Subject_Name` varchar(200) NOT NULL,
    `Pass_word` varchar(200) NOT NULL
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';

mysqli_query($con, $tables);

   ?>